from __future__ import annotations

# Keep exact Amazon report type values centralized to avoid typos across services.

# Listings / inventory basics
LISTINGS_ALL_DATA = "GET_MERCHANT_LISTINGS_ALL_DATA"
OPEN_LISTINGS = "GET_FLAT_FILE_OPEN_LISTINGS_DATA"
INVENTORY = "GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA"
FBA_INVENTORY_PLANNING = "GET_FBA_INVENTORY_PLANNING_DATA"
AFN_INVENTORY = "GET_AFN_INVENTORY_DATA"
RESERVED_INVENTORY = "GET_RESERVED_INVENTORY_DATA"
RESTOCK_INVENTORY = "GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT"
STRANDED_INVENTORY = "GET_STRANDED_INVENTORY_UI_DATA"
FBA_RECOMMENDED_REMOVAL = "GET_FBA_RECOMMENDED_REMOVAL_DATA"

# Sales / traffic / orders
SALES_AND_TRAFFIC = "GET_SALES_AND_TRAFFIC_REPORT"
ALL_ORDERS_BY_ORDER_DATE = "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL"
ALL_ORDERS_BY_LAST_UPDATE = "GET_FLAT_FILE_ALL_ORDERS_DATA_BY_LAST_UPDATE_GENERAL"
FBA_FULFILLED_SHIPMENTS = "GET_AMAZON_FULFILLED_SHIPMENTS_DATA_GENERAL"

# Returns / concessions
RETURNS_BY_RETURN_DATE = "GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE"
FBA_CUSTOMER_RETURNS = "GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA"
FBA_REPLACEMENTS = "GET_FBA_FULFILLMENT_CUSTOMER_SHIPMENT_REPLACEMENT_DATA"

# FBA finance / inventory cost
FBA_ESTIMATED_FEES = "GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA"
FBA_REIMBURSEMENTS = "GET_FBA_REIMBURSEMENTS_DATA"
FBA_STORAGE_FEES = "GET_FBA_STORAGE_FEE_CHARGES_DATA"
FBA_LONG_TERM_STORAGE_FEES = "GET_FBA_FULFILLMENT_LONGTERM_STORAGE_FEE_CHARGES_DATA"
FBA_OVERAGE_FEES = "GET_FBA_OVERAGE_FEE_CHARGES_DATA"
LEDGER_DETAIL_VIEW = "GET_LEDGER_DETAIL_VIEW_DATA"
LEDGER_SUMMARY_VIEW = "GET_LEDGER_SUMMARY_VIEW_DATA"

# Promotions / coupons. Availability varies by account and marketplace.
PROMOTION_PERFORMANCE = "GET_PROMOTION_PERFORMANCE_REPORT"
COUPON_PERFORMANCE = "GET_COUPON_PERFORMANCE_REPORT"

# Settlement reports are Amazon-generated and must be discovered with getReports.
SETTLEMENT_V2 = "GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2"
