from __future__ import annotations

import argparse
from pathlib import Path

from seller_data_pipeline.common.cli import run_cli_main
from seller_data_pipeline.common.logging import configure_logging
from seller_data_pipeline.config.settings import get_settings
from seller_data_pipeline.db.connection import get_connection
from seller_data_pipeline.db.repositories.sku_cost_repo import SkuCostRepo
from seller_data_pipeline.services.sku_cost_service import SkuCostWorkbookService


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Import manually filled SKU standard costs from the xlsx generated by "
            "export_sku_cost_template.py. Default mode is dry-run; use --execute to write."
        ),
    )
    parser.add_argument(
        "--file",
        required=True,
        help="Path to filled sku_cost_template.xlsx.",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually insert/update dbo.amazon_sku_cost. Without this flag, no DB writes occur.",
    )
    parser.add_argument(
        "--update-existing",
        action="store_true",
        help=(
            "Update an existing row when marketplace_id + seller_sku + new_effective_from "
            "already exists. Default is skip existing rows for idempotent re-import."
        ),
    )
    parser.add_argument(
        "--no-close-previous-open",
        action="store_true",
        help=(
            "Do not close the previous open-ended cost row. Default execute mode closes older "
            "effective_to=NULL rows for the same SKU to avoid overlapping cost periods."
        ),
    )
    args = parser.parse_args()

    settings = get_settings()
    configure_logging(settings.log_level)
    workbook_path = Path(args.file)
    if not workbook_path.exists():
        raise SystemExit(f"Workbook not found: {workbook_path}")

    service = SkuCostWorkbookService()
    with get_connection(settings=settings) as connection:
        result = service.import_workbook(
            repo=SkuCostRepo(connection),
            workbook_path=workbook_path,
            dry_run=not args.execute,
            update_existing=args.update_existing,
            close_previous_open=not args.no_close_previous_open,
        )

    print(f"SKU cost import status={result.status} dry_run={result.dry_run}")
    print(f"file={result.workbook_path}")
    print(
        "candidate_rows="
        f"{result.candidate_rows} inserted={result.inserted_rows} updated={result.updated_rows} "
        f"skipped_existing={result.skipped_existing_rows} closed_previous={result.closed_previous_rows}"
    )
    if result.issues:
        print("issues:")
        for issue in result.issues:
            seller_sku = issue.seller_sku or "-"
            print(f"- row={issue.row_number} sku={seller_sku} {issue.severity}: {issue.message}")
    if result.has_errors:
        raise SystemExit(2)
    if result.dry_run:
        print("Dry-run only. Re-run with --execute after reviewing the summary.")


if __name__ == "__main__":
    run_cli_main(main)
