-- SellerDataPipeline seed 001: core manual-first job configuration.
-- Safe to re-run. Existing job_key rows are updated in place.

MERGE dbo.pipeline_job_config AS target
USING (VALUES
    (
        'manual.ingest.ads_sp_core.us',
        'ingest',
        'Ingest Sponsored Products Ads reports',
        'amazon_ads',
        'ATVPDKIKX0DER',
        '3917953989967300',
        'ads_sp_core',
        'spCampaigns,spTargeting,spSearchTerm,spAdvertisedProduct',
        'amazon_ads_sp_campaign_daily;amazon_ads_sp_targeting_daily;amazon_ads_sp_search_term_daily;amazon_ads_sp_advertised_product_daily',
        'scripts/ingest_ads_reports.py',
        '{"profile_id":"3917953989967300","marketplace_id":"ATVPDKIKX0DER"}',
        10,
        'day',
        1,
        14,
        1,
        'manual_first',
        1,
        'Run daily in automation; during manual stage run weekly or after advertising changes.'
    ),
    (
        'manual.ingest.listing_snapshot.us',
        'ingest',
        'Ingest merchant listings snapshot',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'listing_snapshot',
        'GET_MERCHANT_LISTINGS_ALL_DATA',
        'amazon_listing_snapshot',
        'scripts/ingest_listing_snapshot.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        20,
        'week',
        1,
        1,
        0,
        'manual_first',
        1,
        'Small catalogue can run weekly; run immediately after material listing changes.'
    ),
    (
        'manual.ingest.inventory_snapshot.us',
        'ingest',
        'Ingest FBA inventory snapshot',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'inventory_snapshot',
        'GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA',
        'amazon_inventory_daily',
        'scripts/ingest_inventory_snapshot.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        30,
        'day',
        1,
        1,
        0,
        'manual_first',
        1,
        'Primary source for current stock balance in weekly operations reports.'
    ),
    (
        'manual.ingest.sales_traffic.us',
        'ingest',
        'Ingest sales and traffic report',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'sales_traffic',
        'GET_SALES_AND_TRAFFIC_REPORT',
        'amazon_sales_traffic_daily;amazon_sales_traffic_asin_daily',
        'scripts/ingest_sales_traffic_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        40,
        'day',
        1,
        7,
        1,
        'manual_first',
        1,
        'Rolling lookback is recommended because sales and traffic can be delayed.'
    ),
    (
        'manual.ingest.settlement.us',
        'ingest',
        'Ingest settlement transactions',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'settlement',
        'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
        'amazon_settlement_transaction',
        'scripts/ingest_settlement_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        50,
        'week',
        1,
        60,
        1,
        'manual_first',
        1,
        'Settlement is Amazon-generated; future automation should discover new reports.'
    ),
    (
        'manual.ingest.orders.us',
        'ingest',
        'Ingest all orders report',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'orders',
        'GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL',
        'amazon_order_item',
        'scripts/ingest_orders_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        60,
        'day',
        1,
        7,
        1,
        'manual_first',
        1,
        'Used for order/SKU detail and promotion IDs; privacy guard remains required.'
    ),
    (
        'manual.ingest.fba_reimbursements.us',
        'ingest',
        'Ingest FBA reimbursements report',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'fba_reimbursements',
        'GET_FBA_REIMBURSEMENTS_DATA',
        'amazon_fba_reimbursement',
        'scripts/ingest_fba_reimbursements_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        70,
        'week',
        1,
        30,
        1,
        'manual_first',
        1,
        'Reimbursements can arrive late; use a longer lookback window.'
    ),
    (
        'manual.ingest.fba_fee_preview.us',
        'ingest',
        'Ingest FBA fee preview report',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'fba_fee_preview',
        'GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA',
        'amazon_fba_fee_preview',
        'scripts/ingest_fba_fee_preview_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        80,
        'week',
        1,
        1,
        0,
        'manual_first',
        1,
        'Estimated fees are useful for planning; final fees come from settlement.'
    ),
    (
        'manual.ingest.promotion_coupon.us',
        'ingest',
        'Ingest promotion and coupon reports',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'promotion_coupon',
        'GET_PROMOTION_PERFORMANCE_REPORT,GET_COUPON_PERFORMANCE_REPORT',
        'amazon_promotion_performance;amazon_promotion_product_performance;amazon_coupon_performance;amazon_coupon_asin',
        'scripts/ingest_promotion_coupon_reports.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        90,
        'day',
        1,
        30,
        1,
        'manual_first',
        1,
        'Run daily during active coupons, Prime Day or promotional campaigns.'
    ),
    (
        'manual.ingest.inventory_ledger.us',
        'ingest',
        'Ingest inventory ledger reports',
        'sp_api_reports',
        'ATVPDKIKX0DER',
        NULL,
        'inventory_ledger',
        'GET_LEDGER_SUMMARY_VIEW_DATA,GET_LEDGER_DETAIL_VIEW_DATA',
        'amazon_inventory_ledger_summary_daily;amazon_inventory_ledger_detail',
        'scripts/ingest_inventory_ledger_reports.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        100,
        'week',
        1,
        14,
        1,
        'manual_first',
        1,
        'Use for stock movement explanation and inventory audit, not primary balance.'
    ),
    (
        'manual.process.profit_weekly.us',
        'process',
        'Calculate weekly profit metrics',
        'internal',
        'ATVPDKIKX0DER',
        NULL,
        'profit_calculation',
        NULL,
        NULL,
        'scripts/calculate_profit_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER","period":"weekly"}',
        200,
        'week',
        1,
        7,
        1,
        'manual_first',
        0,
        'Placeholder until feature_profit_calculation.md and script are implemented.'
    ),
    (
        'manual.report.weekly_operations.us',
        'report',
        'Generate weekly operations report',
        'internal',
        'ATVPDKIKX0DER',
        NULL,
        'weekly_operations_report',
        NULL,
        NULL,
        'scripts/generate_weekly_operations_report.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        210,
        'week',
        1,
        7,
        1,
        'manual_first',
        0,
        'Placeholder until weekly report generation is implemented.'
    ),
    (
        'manual.email.weekly_operations.us',
        'email',
        'Send weekly operations report email',
        'email',
        'ATVPDKIKX0DER',
        NULL,
        'weekly_report_email',
        NULL,
        NULL,
        'scripts/send_weekly_report_email.py',
        '{"marketplace_id":"ATVPDKIKX0DER"}',
        220,
        'week',
        1,
        NULL,
        NULL,
        'manual_first',
        0,
        'Placeholder. First version should generate a draft or require manual approval.'
    )
) AS source (
    job_key,
    job_group,
    job_name,
    source_system,
    marketplace_id,
    profile_id,
    data_domain,
    report_type,
    target_table,
    script_path,
    default_args_json,
    manual_run_order,
    recommended_cadence_unit,
    recommended_cadence_value,
    default_lookback_days,
    data_window_lag_days,
    execution_phase,
    enabled,
    notes
)
ON target.job_key = source.job_key
WHEN MATCHED THEN
    UPDATE SET
        job_group = source.job_group,
        job_name = source.job_name,
        source_system = source.source_system,
        marketplace_id = source.marketplace_id,
        profile_id = source.profile_id,
        data_domain = source.data_domain,
        report_type = source.report_type,
        target_table = source.target_table,
        script_path = source.script_path,
        default_args_json = source.default_args_json,
        manual_run_order = source.manual_run_order,
        recommended_cadence_unit = source.recommended_cadence_unit,
        recommended_cadence_value = source.recommended_cadence_value,
        default_lookback_days = source.default_lookback_days,
        data_window_lag_days = source.data_window_lag_days,
        execution_phase = source.execution_phase,
        enabled = source.enabled,
        notes = source.notes,
        updated_at = SYSUTCDATETIME()
WHEN NOT MATCHED THEN
    INSERT (
        job_key,
        job_group,
        job_name,
        source_system,
        marketplace_id,
        profile_id,
        data_domain,
        report_type,
        target_table,
        script_path,
        default_args_json,
        manual_run_order,
        recommended_cadence_unit,
        recommended_cadence_value,
        default_lookback_days,
        data_window_lag_days,
        execution_phase,
        enabled,
        notes
    )
    VALUES (
        source.job_key,
        source.job_group,
        source.job_name,
        source.source_system,
        source.marketplace_id,
        source.profile_id,
        source.data_domain,
        source.report_type,
        source.target_table,
        source.script_path,
        source.default_args_json,
        source.manual_run_order,
        source.recommended_cadence_unit,
        source.recommended_cadence_value,
        source.default_lookback_days,
        source.data_window_lag_days,
        source.execution_phase,
        source.enabled,
        source.notes
    );
GO
