-- Example only. Replace with real SKU costs before calculating profit.
-- INSERT INTO dbo.amazon_sku_cost
-- (marketplace, sku, asin, product_cost, first_mile_cost, packaging_cost, other_unit_cost, currency, effective_from, remark)
-- VALUES
-- ('US', 'EXAMPLE-SKU', 'B000000000', 1.50, 0.30, 0.05, 0.00, 'USD', '2026-01-01', 'Example row only');
